#!/usr/bin/env ruby
require 'rubygems'
require 'eventmachine'
require 'em-websocket'
require 'readline'
require 'json'
require 'pp'

port = 8088
port = ARGV.first.to_i if ARGV.size > 0

EM::run do
  @channel = EM::Channel.new
  puts 'iPhone JS Console'
  puts "start server - port:#{port}"

  EM::WebSocket.start(:host => "0.0.0.0", :port => port) do |ws|
    ws.onopen{
      sid = @channel.subscribe{|mes|
        ws.send(mes)
      }
      puts "<#{sid}> connected!!"

      ws.onmessage{|mes|
        print "<#{sid}> "
        begin
          o = JSON.parse(mes)
          puts ''
          pp o
        rescue
          puts mes
        end
      }

      ws.onclose{
        puts "<#{sid}> disconnected"
        @channel.unsubscribe(sid)
      }
    }
  end

  EM::defer do
    loop do
      line = Readline.readline("> ", true)
      @channel.push(line) if line.size > 0
    end
  end

end
