#!/usr/bin/env ruby
require 'rubygems'
require 'em-websocket'

EM::run do

  puts 'iPhone JS Console Start'
  @channel = EM::Channel.new

  EM::WebSocket.start(:host => "0.0.0.0", :port => 8088) do |ws|
    ws.onopen{
      sid = @channel.subscribe{|mes|
        ws.send(mes)
      }
      puts "<#{sid}> connected!!"
      @channel.push("hello <#{sid}>")

      ws.onmessage{|mes|
        puts "<#{sid}> #{mes}"
      }

      ws.onclose{
        puts "<#{sid}> disconnected"
        @channel.unsubscribe(sid)
      }
    }
  end

end
